name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gcc-build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gcc: [4.9, 5, 7, 9, 10]
        std: [11, 14, 17]
        exclude:
          - gcc: 4.9
            std: 17
        include:
          - gcc: 9
            std: 20
          - gcc: 10
            std: 20
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Test
      run: docker run --rm -u $(id -u):$(id -g) -v $PWD:/data nakatt/gcc:${{ matrix.gcc }} make DEBUG=0 STDCXX=${{ matrix.std }} TOOLCHAIN=gcc test

  clang-build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        clang: [7, 11]
        std: [11, 14, 17]
        include:
          - clang: 11
            std: 20
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Test
      run: docker run --rm -u $(id -u):$(id -g) -v $PWD:/data nakatt/clang:${{ matrix.clang }} make DEBUG=0 STDCXX=${{ matrix.std }} TOOLCHAIN=clang test

  windows-msvc-build:
    runs-on: windows-latest
    strategy:
      matrix:
        std: [11, 14, 17]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Add cl.exe to PATH
      uses: seanmiddleditch/gha-setup-vsdevenv@v3
    - name: Test
      run: |
        make DEBUG=0 STDCXX=${{ matrix.std }} TOOLCHAIN=msvc14 test
        make DEBUG=0 STDCXX=${{ matrix.std }} TOOLCHAIN=msvc141 test
        make DEBUG=0 STDCXX=${{ matrix.std }} TOOLCHAIN=msvc142 test
